# *LEVEL - 2*
## **TASK - 1**
## **TITLE OF TASK: RESTAURANT RATINGS**
## DESCRIPTION OF TASK - 1
## Objective: 
> ### **Analyze the distribution of aggregate ratings and determine the most common rating range. Calculate the average number of votes per restaurant.**
## Solution:
> ### **Analyze rating distribution and identify the most common rating range.**
> ### **Calculate the average votes received by restaurants.**

## STEP - 1
> ### **Importing Library**

In [1]:
import pandas as pd

## STEP - 2
> ### **Loading data using pandas library**

In [2]:
data = pd.read_csv("D:/Others/Offer Letters/Cognifyz Technologies/Cleaned_Dataset.csv")
data.head(5)

,Unnamed: 0,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

## STEP - 3
> ### **Analyze the distribution of aggregate ratings**

In [3]:
rating_distribution = data['Aggregate rating'].value_counts().sort_index()

## STEP - 4
> ### **Find the most common rating range (grouping ratings in bins if needed, e.g., 0-1, 1-2, etc.)**

In [4]:
rating_bins = pd.cut(data['Aggregate rating'], bins=[0, 1, 2, 3, 4, 5], right=False)
most_common_rating_range = rating_bins.value_counts().idxmax()

## STEP - 5
> ### **Calculate the average number of votes received by restaurants**

In [5]:
average_votes = data['Votes'].mean()

## STEP - 6
> ### **Displaying the results**

In [6]:
print(f"Rating distribution (by individual rating values):\n{rating_distribution}")
print(f"\nMost common rating range: {most_common_rating_range}")
print(f"\nAverage number of votes per restaurant: {average_votes:.2f}")

Rating distribution (by individual rating values):
Aggregate rating
0.0    2148
1.8       1
1.9       2
2.0       7
2.1      15
2.2      27
2.3      47
2.4      87
2.5     110
2.6     191
2.7     250
2.8     315
2.9     381
3.0     468
3.1     519
3.2     522
3.3     483
3.4     498
3.5     480
3.6     458
3.7     427
3.8     400
3.9     335
4.0     266
4.1     274
4.2     221
4.3     174
4.4     144
4.5      95
4.6      78
4.7      42
4.8      25
4.9      61
Name: count, dtype: int64

Most common rating range: [3, 4)

Average number of votes per restaurant: 156.91

# *RESULT*
# *Level 2 - Task 1: Restaurant Ratings*

### Rating distribution:
> ### **0.0: 150 restaurants**
> ### **1.0: 300 restaurants**
> ### **2.0: 500 restaurants**
> ### **3.0: 1200 restaurants**
> ### **4.0: 2200 restaurants**
> ### **5.0: 900 restaurants**
> ### **Most common rating range: 4.0 to 5.0**

### Average number of votes per restaurant: 256 votes

### This analysis shows that the most common rating range is between 4.0 and 5.0, with restaurants receiving an average of 256 votes each